GET http://localhost:3000/todos
###

GET http://localhost:3000/todos/1111
###

POST http://localhost:3000/todos
Content-Type: application/json

{
    "title": "dancing",
    "completed": false,
    "description": "on disco nights"
}
###

PUT http://localhost:3000/todos/1111
Content-Type: application/json

{
    "title": "eating",
    "completed": true,
    "description": "for muscle building"
}
###

DELETE http://localhost:3000/todos/1111
###


# Hard todo

GET http://localhost:3001/todos
###

POST http://localhost:3001/todos
Content-Type: application/json

{
    "title": "express",
    "description": "work on express servers"
}
###

DELETE http://localhost:3001/todos/7860
